In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv(r"C:\Users\Dell\Desktop\ML Lab\MVRdata.csv")
data

    x0        x1        x2          y
0    1  1.150851  3.575864   9.636156
1    1  2.291188  4.361524  15.004626
2    1  2.955033  3.242733  17.092429
3    1  1.068906  1.668891   6.732142
4    1  2.941606  3.643394  15.484327
..  ..       ...       ...        ...
95   1  0.361283  2.708396   9.622291
96   1  2.165122  0.969692  10.590041
97   1  3.094731  2.563719  12.594549
98   1  4.698886  0.997623  15.971608
99   1  0.529371  2.549773   9.024761

[100 rows x 4 columns]

In [2]:
train_data = data[ :80]
train_data_X = train_data[["x0", "x1", "x2"]].to_numpy()
train_data_Y = train_data[["y"]].to_numpy()
train_data_X
train_data_Y

#Here training data preparation is happening
#1st 80 rows are used

array([[ 9.63615622],
       [15.00462559],
       [17.09242911],
       [ 6.7321419 ],
       [15.48432719],
       [ 8.84769772],
       [10.91576525],
       [ 6.14313326],
       [17.23128362],
       [ 8.69576165],
       [21.48555278],
       [17.01518259],
       [ 9.86253579],
       [21.02758506],
       [12.11901633],
       [11.63000924],
       [14.69656677],
       [ 6.25810253],
       [15.81516388],
       [16.65068236],
       [15.00977524],
       [11.91665073],
       [20.05923966],
       [ 9.93190244],
       [ 9.33718592],
       [19.96673924],
       [17.26393253],
       [ 6.43782925],
       [ 8.76061564],
       [17.39994761],
       [18.58015804],
       [16.83207172],
       [12.40162977],
       [14.13079803],
       [14.23867676],
       [ 8.29741128],
       [19.01972504],
       [16.20353188],
       [14.36131172],
       [19.90352492],
       [11.02908131],
       [15.94551033],
       [16.95006802],
       [ 8.0682205 ],
       [15.21692736],
       [23.90201111],
       [14.83305226],
       [ 5.49572374],
       [10.05499755],
       [ 9.79339572],
       [13.96462176],
       [12.57899715],
       [15.82843329],
       [ 8.97404858],
       [ 8.67164555],
       [13.44041501],
       [22.13555717],
       [ 7.31551304],
       [ 9.52651802],
       [14.79998678],
       [13.38124271],
       [12.35397702],
       [16.60001023],
       [10.60334403],
       [19.33226236],
       [16.82606112],
       [12.96822691],
       [19.79733795],
       [11.50742418],
       [11.3596205 ],
       [ 9.41036063],
       [12.46528621],
       [16.13753053],
       [ 8.52172793],
       [10.47508272],
       [10.65313233],
       [12.04312021],
       [17.16264457],
       [19.70046911],
       [ 6.35691557]])

In [3]:
test_data = data[80: ]
test_data_X = test_data[["x0", "x1", "x2"]].to_numpy()
test_data_Y = test_data[["y"]].to_numpy()
test_data_X
test_data_Y

#Here testing data preparation is happening
#Remaining data after 80 Rows are used

array([[ 6.4166665 ],
       [14.38576566],
       [15.23840502],
       [12.09287894],
       [13.10225749],
       [16.33460251],
       [19.87687845],
       [17.25978528],
       [11.83035223],
       [16.9966098 ],
       [ 7.87391482],
       [13.78097383],
       [ 6.79158762],
       [16.96019645],
       [13.30666354],
       [ 9.62229059],
       [10.59004052],
       [12.59454945],
       [15.97160805],
       [ 9.02476117]])

In [4]:
Xt = np.transpose(train_data_X)
inv_of_Xt_x_X = np.linalg.inv(np.dot(Xt, train_data_X))
Weight_matrix = np.dot(inv_of_Xt_x_X, np.dot(Xt, train_data_Y))

#Weight matrix is calculated using pseudo inverse

In [5]:
Y_pred = np.dot(test_data_X, Weight_matrix)
test_data = test_data.drop(columns="x0")
test_data["Y_pred"] = Y_pred
test_data
absolute_error = squared_error = 0

#Bias column from test data is dropped and then prediction happens

In [6]:
num_test_data = len(test_data)
for index, row in test_data.iterrows():
    error = row["y"] - row["Y_pred"]
    absolute_error += abs(error)
    squared_error += error * error
    
#After prediction, squared error is calculated for each point

In [7]:

mean_absolute_error = absolute_error / num_test_data
mean_squared_error = squared_error / num_test_data

In [8]:
print("Mean Absolute Error: ", mean_absolute_error)
print("Mean Squared Error: ", mean_squared_error)

Mean Absolute Error:  1.2865745764745458
Mean Squared Error:  2.003837032432212